const r_text = [
    'I was just thinking about you!',
    'Welcome, friend!',
    'TRANS RIGHTS ARE HUMAN RIGHTS',
    'JESS IS A DWEEB',
    'WIFE :)',
    'IF YOUR NAME IS JESS I LOVE YOU',
    'SNOWEI IS A DWEEB',
    'HI SYLVIE!! :3 :3 AWAWAA',
    'I LOVE THE WORLD',
    'AWAWAWAWAWAWWAWAWAWAWAW',
    'MADDIE MOMENTS',
    'EVE IS EPIC',
    'AIR POD NANO (RABET)',
    'ALSO CHECK OUT CODIEGOTLOST!',
    'CASSETTEPUNKS UNITE',
    'HACK THE PLANET',
    'The world is a beautiful place',
    'You have great ideas.',
    'When I grow up I want to be you!',
    'I appreciate all of your opinions.',
    'GORBY MORBY!',
    'HAPPY BAPPY',
    'YOU UPLOADED IT, YOU UNLOAD IT!',
    'LISTEN TO IDA',
    'LISTEN TO DIDELPHIDAE',
    'LISTEN TO MEMODEMO',
    '867-5309',
    '4, 8, 15, 16, 23, 42',
    'I AM ACTUALLY ENTRAPTA IRL',
    'It\'s on the mouse!',
    'barkbarkbarkabkarbakrba awaawa',
    'this too shall pass',
    'lying your hair in a spiral',
    'everything\'s not lost',
    'I would speak to you in song',
    'wail sometimes, its good for the soul',
    'we have had such conversations in dead silence',
    'i want to become something destroyed by love',
    'MARS MARS MARS MARS MARS',
    'I\'ll be there at your side, just you try and stop me',
    '*paws at you*',
    'congratulations!',
    'what if jfk\'s head just did that',
    'lets blow this posicle man',
    'what a shame',
    'flowergirls unite',
    'slimegirls also welcome',
    'autumn is pretty',
    'lizzy lizzy lizzy lizzy lizzy owo',
    'have you notice how the wind sings through the trees',
    'i dont want to end this season on a bad episode',
    'read YKK!',
    'I will never stop being proud of you',
    'mommy i mean mommy, shit, i mean. mommy',
    'it\'s business time',
    'I\'m goin to sleep!',
    'cum',
    'remember, switching to your second gender is always faster than reloading',
    'POT ROAST',
    'Yo!',
    'Women should kiss eachother',
    '1st law of robotics you must kiss girls',
    '2nd law of robotics you must be trans',
    'I don\'t know poop from apple sauce',
    'welcome to headspace',
    'big floppy puppy dog ears = gender affirming',
    'hello motherfucker',
    'hello monsterfucker',
    'snowei reference #2 :3',
    'https://hirob.in was my dad',
    'You\'re cringe, why do you think that is?',
    'I\'m not cringe.',
    'if you see this one you win $1 from me (if seen before March 20th 2024)',
    'super mario in real life',
    'mcchicken parm...',
    'I\'m going to bloom',
    'joe if you\'re reading this look outside your window',
    'NOW ITS TIME TO REALLY EXPLODE',
    'I could learn to love like you',
    'It\'s going to be okay!',
    'I ASPLODE YOU HEAD',
    'id rather be frotting',
    'I have fallen so deeply in love with the world',
    'You can find my song in the CBR',
    'I am a cluster of superpositions held together by will',
    'And for all that I cannot say with word, hear in my kiss',
    'Hello Mellow!',
    'Hello Miss',
    'Professionally Pethetic',
    'Retrofuturist Cassettepunk and loud faggot',
    'Dont piss me off Im close to levelling up and you look like just enough XP',
    'Giggle at the ghosties!',
    'You can outsilly despair',
    'Despair cannot exist in the same room as whimsy',
    'the 404 challenge more like cuck challenge',
    'My human experience is rare and beautiful',
    'Remember, switching to your secondary personality is always faster than reloading',
    'Now I\'ll give you something really flashy to cheer for',
    'WOMEN',
    'Just clocked in at the i love you factory',
    'Oh god I\'ve never felt this gay before in my life',
    'why cant you use sheers on cows for leather',
    'easel'
];
const idx = Math.floor(Math.random() * r_text.length);
document.getElementById('random').style = "color: orange;  position: static; margin-top: -20px;"
document.getElementById('random').innerText = r_text[idx];

//transform: translate(200px, -40px) rotate(-15deg); 